/* FILE GENERATED by mkgenconf -- DO NOT MODIFY */
#define GET_EMPTY_INODE(sb) get_empty_inode()
#define SET_CPUS_ALLOWED	1
#define STREAMS_REGPARM	0
#define CCREGPARM	0
#define _RP     
#define USE_NAMEI_H 1
#define KOBJ_USES_KREF 1
